close-open-trades-on-exit: true
candlestick-interval: HALF_HOURLY

take-profit:
    enabled: true
    percent: 8.0

stop-loss:
    enabled: false
    percent: 2.0

trailing-stop:
    enabled: false
    arm-at: 0.4
    percent: 0.5

buy:
    min-signals: -1
    percent-of-bal: 60.0
    dont-buy-if-more-sell-signals: true
    min-usd: 20.0
    max-usd: -1.0
    
sell:
    min-signals: -1
    based-on-indicators: true
    sell-all: false
