show-buy-sell-signals: true
heikin-ashi-candles: true
crypto: BTC
fiat: USDT
buy-sell-fee-percent: 0.1

downloader:
    break-seconds: 3

backtest:
    show-gui: true
    starting-balance: 100.0
    
simulation:
    show-gui: true
    starting-balance: 100.0

live-trading:
    show-gui: true
    max-order-retries: 3
    order-retry-delay: 500
    market-order-on-retry: 3

indicators:
    ema:
        show-on-chart: true
        color: 0x0F74E7
        line-width: 2.0
    wma:
        show-on-chart: true
        color: 0x8620E5
        line-width: 2.0
    rsi:
        show-on-chart: true
        midline: true
        color: 0x7E44F1
        overbought-color: 0xF33232
        oversold-color: 0x36F54F
        midline-color: 0x6C6C6C
        line-width: 1.5
