simulation-starting-balance: 100.0
show-buy-sell-signals: true
heikin-ashi-candles: true

downloader:
    break-seconds: 3

backtest:
    show-gui: true
    starting-balance: 100.0
    
simulation:
    show-gui: true
    starting-balance: 100.0
    coin: BTCUSD

live-trading:
    show-gui: true
    coin: BTCUSD

indicators:
    ema:
        show-on-chart: true
        color: 0x0F74E7
        line-width: 2.0
    wma:
        show-on-chart: true
        color: 0x8620E5
        line-width: 2.0
    rsi:
        show-on-chart: true
        midline: true
        color: 0x7E44F1
        overbought-color: 0xF33232
        oversold-color: 0x36F54F
        midline-color: 0x6C6C6C
        line-width: 1.5
