max-open-trades: 1
close-open-trades-on-exit: true

take-profit:
    enabled: true
    percent: 10.0

stop-loss:
    enabled: true
    percent: 2.0

trailing-stop:
    enabled: true
    arm-at: 0.1
    percent: 0.2

buy:
    min-signals: -1
    percent-of-bal: 25.0
    dont-buy-if-more-sell-signals: true
    min-usd: 1.0
    max-usd: -1.0
    
sell:
    min-signals: -1
    based-on-indicators: true
    sell-all: false
